// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwosaoz4x8JN3x-tO6IQMLC-eouUZTkPY',
    appId: '1:677745574096:web:c03d5a4244d88960d75ed5',
    messagingSenderId: '677745574096',
    projectId: 'ecom-admin-web-flutter-e3f8e',
    authDomain: 'ecom-admin-web-flutter-e3f8e.firebaseapp.com',
    storageBucket: 'ecom-admin-web-flutter-e3f8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHrT4-rUV1FASPzHAbKm7BpqNf-v_c0qg',
    appId: '1:677745574096:android:aaa8362a1cae0ce4d75ed5',
    messagingSenderId: '677745574096',
    projectId: 'ecom-admin-web-flutter-e3f8e',
    storageBucket: 'ecom-admin-web-flutter-e3f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-KAtoxExJ_joZU22o9YnapEktouSvZk',
    appId: '1:677745574096:ios:c7865fd172f1d85fd75ed5',
    messagingSenderId: '677745574096',
    projectId: 'ecom-admin-web-flutter-e3f8e',
    storageBucket: 'ecom-admin-web-flutter-e3f8e.firebasestorage.app',
    iosBundleId: 'com.example.webByFlutterEcomAdmin',
  );
}
