// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtq5G86zQUYE-yuS9DxdHp8kMZOaR-SF4',
    appId: '1:659081979812:web:6b8b1cc7666b26230fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    authDomain: 'chat-app-9b76b.firebaseapp.com',
    storageBucket: 'chat-app-9b76b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xbGFmHOhm7cJvzw2yAgYpmVAjG8MCoU',
    appId: '1:659081979812:android:df91374f773c048c0fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    storageBucket: 'chat-app-9b76b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYa4nAhd9QAwE85IhA_yQ6qflzGRB_6Gw',
    appId: '1:659081979812:ios:2633a30a0a41c0170fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    storageBucket: 'chat-app-9b76b.appspot.com',
    androidClientId: '659081979812-o6dsd67kfe0gpn80cdckvd9f736ok54t.apps.googleusercontent.com',
    iosClientId: '659081979812-e5kj008rifurt2gsls6in7508t0qoii5.apps.googleusercontent.com',
    iosBundleId: 'com.example.webByFlutterEcomAdmin',
  );

}